transport.go

The certificate chain used for the handshake is relatively small (it fits in 2 packets). This reduces the risk that an attacker will use libp2p nodes for reflection attacks.
At some point, we should require source address validation when under load (#6).

disable source address validation

---

conn.go
conn_test.go
listener.go
quic_multiaddr.go
quic_multiaddr_test.go
transport.go

Fixes #15.
I recently merged https://github.com/lucas-clemente/quic-go/pull/1407 in quic-go, which allows running multiple dialers on the same packet conn. We can already use that in libp2p.
Note that quic-go can't *yet* run listeners and dialers on the same packet conn. I'm working on that.

use a single packet conn for all outgoing connections

---

.travis.yml
Makefile
package.json

Closes #11.
The gx build works now, however, in order to publish quic-go, I had to use a custom version of gx to work around https://github.com/whyrusleeping/gx/issues/185.

make the gx build work

---

crypto.go

Fixes #22.
By setting the `NotBefore` and `NotAfter` in the certificate, we're leaking the exact start time of a node. I'm not sure if we're doing that at other places as well, but if not, we could add some randomisation here.

generate certificates that are valid for 180 days

---

.gx/lastpubver
conn.go
listener.go
package.json
transport.go

This is the version that's supposed to go into the next go-ipfs release.

update to the latest quic-go, gx publish

---

.travis.yml

Currently half of the Travis builds are failing due to `go get` errors. 🙄

use travis_retry for go get on Travis

---

conn_test.go
libp2pquic_suite_test.go
listener.go
listener_test.go
reuse.go
reuse_test.go

Fixes #70.
This PR implements the sweeper as suggested in #63.
The sweeper runs every 30 seconds and removes connections that have been unused for more than 10 seconds. In order to not leak go routines, it stops itself once a `reuse` doesn't have any more active connections, and is restarted as soon as a connection is added.

implement a garbage-collector for unused reuse connections

---

go.mod
netlink_android.go
netlink_linux.go
netlink_other.go
reuse.go

Hi there !
I work at Berty and actually use this lib along with libp2p on mobile.
Since a recent change and more particularly since the introduction of netlink for the reuse port, we can't use this lib anymore on Android.
Android doesn't allow netlink_xfrm & netlink_nflog in his base policy in enforce mode (see [here](https://android.googlesource.com/platform/system/sepolicy/+/3aa1c1725ea2b6fd452c5771629dcfc50a351538/public/app.te#396)).
this cause a _permission denied_ when NewTransport method is called on android:
```
type=1400 audit(0.0:98079): avc: denied { create } for scontext=u:r:untrusted_app:s0:c182,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c182,c256,c512,c768 tclass=netlink_xfrm_socket permissive=0
```
However it's look like that only *netlink route* is needed, so we tried to …

Use specific netlink families for android

---

libp2pquic_suite_test.go
netlink_other.go
reuse_base.go
reuse_linux_test.go
reuse_not_win.go
reuse_test.go
reuse_win.go

make reuse work on Windows

---

go.mod
go.sum

v0.14.3 contains a workaround for a panic in the Go ChaCha20 implementation: https://github.com/lucas-clemente/quic-go/pull/2331

update quic-go to v0.14.3

---

conn_test.go

https://github.com/libp2p/go-libp2p-core/pull/105 breaks the key comparison in the connection tests here. It's better to use the `Key.Equals()` methods that's intended to compare keys.

fix key comparisons in tests

---

go.mod
go.sum

v0.15.0 shipped with a broken ChaCha header protection. Let's hope nobody deployed it yet.

update quic-go to v0.15.1

---

transport.go

Not sure if this is really necessary, but it doesn't hurt to use the resolved address here.

use the resolved address for RemoteMultiaddr()

---

conn_test.go
filtered_conn.go
go.mod
go.sum
libp2pquic_suite_test.go
listener_test.go
reuse_base.go
reuse_linux_test.go
reuse_not_win.go
reuse_test.go
reuse_win.go
transport.go

Fixes #124.
When multiplexing incoming and outgoing connections on the same packet conn, quic-go expects the packet conns to be the same struct. Therefore, filters are applied for incoming and outgoing connections.

add support for multiaddr filtering

---

conn_test.go
go.mod
go.sum
listener.go
transport.go

Fixes #121.
When a QUIC endpoint loses state (e.g. due to a reboot or a crash), it won't be able to decrypt packets that arrive for connection that it previously handled. QUIC uses a stateless reset to allow the peer to quickly detect this condition (and not having to rely on a lengthy connection timeout).
From the outside, a QUIC stateless reset packet looks like any other (Short Header) QUIC packet. An endpoint recognizes a stateless reset by comparing the last 16 bytes of the encrypted packet to a stateless reset token communicated earlier during the connection.
This token can't be tied to any connection state. Instead, it needs to be derived from values that survive a crash of the node. It therefore makes sense to derive it from the node's private key.

use a stateless reset key derived from the private key

---

transport.go
transport_test.go

See https://github.com/libp2p/go-libp2p/issues/841

fix: avoid dialing/listening on dns addresses

---

.gitignore
buffered_write_closer.go
buffered_write_closer_test.go
conn_test.go
listener.go
transport.go

The connection ID used for logging is the destination connection ID chosen by the client, both for the server's and the client's log file. This allows us to easily correlate two log files, if we happen to have logs from both endpoints.
This also means that if a client manages to create two connections with the same destination connection ID in the same microsecond, we will only have the log of one of those connections. I think we can live with that.
Side note: I'll cut a new quic-go release after this PR is merged. I've made quite a few improvements of qlog after the last release.

export qlogs when the QLOGDIR env variable is set

---

conn_test.go
transport.go

Minimally fixes #155. Closes #156.
This is the solution to #155 that's analogous to what we do for other transports: We first finish the cryptographic handshake (which verifies the peer's identity), and then afterwards close the connection when the connection gater doesn't like that peer's ID.

close the connection when it is refused by InterceptSecured

---

filtered_conn.go

Cherry-picked from #156, while we sort the discussion out.

fix a potential nil-pointer panic.

---

filtered_conn.go

Reverts libp2p/go-libp2p-quic-transport#158. Not necessary as the `filteredConn` is only created when a gater exists.

Revert "fix a potential nil-pointer panic."

---

go.mod
go.sum

v0.16.0 removes support for draft-27 and adds support for draft-28.

update quic-go to v0.16.0

---

go.mod
go.sum

This version supports both draft-28 and draft-29, with draft-29 as the preferred version (the version that's first used on dial attempts).

update quic-go to v0.16.2

---

go.mod
go.sum

Compared to v0.16.2, v0.17.1 drops support for QUIC draft-28.
This is safe to do now, since the only IPFS releases that only supported draft-28 (and didn't support draft-29 yet) were the early rcs for v0.6.0. The last rc and the final release both already support draft-29.

update quic-go to v0.17.1

---

go.mod
go.sum

v0.17.2 is v0.17.1 with https://github.com/lucas-clemente/quic-go/pull/2640 (the fix for https://github.com/ipfs/go-ipfs/issues/7512) cherry-picked.

update quic-go to v0.17.2

---

go.mod
go.sum

This will be necessary to fix issue https://github.com/ipfs/go-ipfs/issues/7526.
Please note the release notes: https://github.com/lucas-clemente/quic-go/releases/tag/v0.17.3. I'm planning to set the `quic.RetireBugBackwardsCompatibilityMode` in go-ipfs.

update quic-go to v0.17.3

---

.github/workflows/interop.sh
.github/workflows/interop.yml
.github/workflows/matrix.jsonc
integrationtests/keygen/keygen.go
integrationtests/main.go
integrationtests/stream/stream.go
integrationtests/stream/stream_old_interface.go

This GitHub Actions config:
1. builds a go-libp2p-quic-transport binary using the release version / Go version specified in `matrix.jsonc`
2. then runs interoperability tests between each and every of combination
This will allow us to have some amount of confidence that releasing a new version of this package doesn't break interoperability with older releases.

use GitHub Actions to test interopability of releases

---

go.mod
go.sum

Already released as [v0.8.2](https://github.com/libp2p/go-libp2p-quic-transport/releases/tag/v0.8.2) (since the stream interface changes are still breaking stuff somewhere in the stack), so we need to make sure that `master` is up-to-date as well.

update quic-go to v0.18.1

---

cmd/client/main.go

Closing the connection triggers writing of the qlog, so this will make debugging easier. It's the right thing to do anyway.

always close the connection in the cmd client

---

.github/workflows/interop.sh
.github/workflows/interop.yml
.github/workflows/matrix.jsonc

Fixes #185.
Not 100% sure if that's the fix, but the qlog I obtained seem to suggest that:
[Archive.zip](https://github.com/libp2p/go-libp2p-quic-transport/files/5529286/Archive.zip)
There's neither a problem with congestion control nor with flow control (stream-, connection-level and stream IDs).

fix hanging multi-transfer interop test

---

go.mod
go.sum

https://github.com/lucas-clemente/quic-go/releases/tag/v0.19.2

update quic-go to v0.19.2

---

.github/workflows/interop.yml
cmd/client/main.go
conn.go
conn_test.go
go.mod
go.sum
integrationtests/conn/conn.go
integrationtests/conn/conn_without_stream_open_context.go
integrationtests/main.go
integrationtests/stream/stream_old_interface.go

Depends on https://github.com/libp2p/go-libp2p-core/pull/172.

change OpenStream to accept a context

---

go.mod
go.sum
tracer.go
tracer_test.go

When running a high-bandwidth connection, qlogging consumes about ~40% CPU, of which 1/4 is spent on JSON encoding an 3/4 is spent on running gzip. Switching from gzip to zstd reduces the time spent on compression to 1/2 of the time spent on JSON encoding. That's a speedup of 6x.
Changing the compression level doesn't actually have a large influence on the file size (in my tests I wasn't able to gain more than 10% by increasing it), so using the fastest compression makes sense here. The zst file will be roughly as large as the gzip file.

switch from gzip to zstd for qlog compression

---

.gitignore
tracer.go
tracer_test.go

Fixes #191. Fixes #192.
I hate that we to make this change, but I don't see any other solution. Compression algorithms keep a lot of internal state, so we shouldn't have too many of them running in parallel. This was already an issue when using gzip (see #192), which got exacerbated by using zstd.
The alternative is to use the file system as a buffer: We qlog into a temporary file `.<name>.qlog.swp`. Once the QUIC connection is closed, we compress that file to `<name>.qlog.zst`.

compress qlogs when the QUIC connection is closed

---

tracer.go

Benchmarks using sample qlog files show that this achieves in improvement in both compression efficiency and compression speed.
More importantly, it prevents us from allocating a 8 MB every time a QUIC connection is closed.
See https://github.com/klauspost/compress/issues/316.

reduce the zstd window size from 8 MB to 32 KB

---

go.mod
go.sum
transport.go

When dialing connections, we still use draft-29, but QUIC v1 is now enabled on the server side. Once a large enough fraction of the network has upgraded, we can switch to v1 for dialing as well.

update quic-go, enable QUIC v1 (RFC 9000)

---

conn_test.go
go.mod
go.sum
listener.go
transport.go
transport_test.go

Needs testing, but feel free to review. 
See https://github.com/libp2p/go-libp2p/issues/1048

hole punching support

---

conn_test.go
transport.go

@mxinden pointed out that comparing peer IDs when hole punching is not necessary. We'll have logic in our DCUtR protocol anyway to assign the role of client and server (we'll need the same logic to coordinate the TCP sim open).

don't compare peer IDs when hole punching

---

.github/workflows/unit.yml
conn_test.go
libp2pquic_suite_test.go
listener_test.go
reuse.go
reuse_test.go
transport.go
transport_test.go

This finally makes it possible to run tests with race detector, and therefore switch to the Unified CI Setup.
Not sure if the implementation of `Transport.Close` here is sufficient to fix #176 though.

implement a Transport.Close that waits for the reuse's GC to finish

---

integrationtests/main.go

I'm wondering what happened here:
1. Why did automerge trigger before even being merged to master?
2. Why did it merge although go-check was not happy?

fix staticcheck

---

reuse.go

close all UDP connections when the reuse is closed

---

cmd/client/main.go
cmd/server/main.go

fix closing of streams in example

---

go.mod
reuse.go

Technically, someone can set net.ipv4.ip_nonlocal_bind=1 to bind to non-existent IP addresses, but I'm comfortable making this change and seeing if anyone complains. I highly doubt it'll have any impact.
If it doesn't work out, we have other options (e.g., catch the "invalid route" error and try again).

reuse the same router until we change listeners

---

conn.go
conn_test.go
listener.go
transport.go

In the swarm, we're calling Close for every connection before it is garbage collected. We therefore don't need to start a Go routine here just to see when a connection is closed.
We now also increment the reuse counter every time a connection is dialed. This simplifies closing the connection.

don't start a Go routine for every connection dialed

---

go.mod
go.sum

No particular reason, just keeping deps up to date.

chore: update klauspost/compress to v1.13.6

---

transport.go

Fixes libp2p/go-libp2p-quic-transport#260
Trying this out to see if races are disappearing

fix data race in allowWindowIncrease

---

conn.go
go.mod
go.sum
listener.go
transport.go
transport_test.go

Fixes #266.
Main "feature" of v0.27.0: A QUIC connection is now called a `quic.Connection`, not `quic.Session` any more.

update quic-go to v0.27.0
